config/routes.rb
Rails.application.routes.draw do
  
 root 'home#index'
  resources :charges, only:[:new,:create,:home]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = 400 # $5 in cents
    @description = 'Description of Charge'
  end

  def create
    amount = 500 # $5 in cents

    @customer = Stripe::Customer.create(email:  params[:stripeEmail],
                                       source: params[:stripeToken])

    @charge = Stripe::Charge.create(customer:    @customer.id,
                                    amount:      amount,
                                    description: 'Rails Stripe customer',
                                    currency:    'cad')
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/charges/create.html.erb
<h2> thanks for paid <strong><%= number_to_currency(@charge.amount/100) %></strong></h2>
<h3>Stripe customer:</h3>
<% debug @customer %>
<h3> Stripe Charge:</h3>
<%= debug @charge %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <div class='stcker'>
	

    <div style="text-align: center">
    <label class="amount">
      <span>Amount:</span>
    </label>

  </article>
<div style="text-align: center">
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="A years subscription" data-amount="1000" data-locale="auto"></script>
</div>
</div>

<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<body>
<h2 style="text-align: center;">SAMSUNG TELEVISION</h2>

<div class="row">
  <div class="column">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlwaLB2n4hXfHNQHlVXE2qgdy33fvnlUt6JnTKNHfGHy7k6KQOJatjCZkzhw&usqp=CAc" style="width:55%"><div style="margin-left: 30px">
    <h5>Samsung 80cm (32 inch) HD Ready LED TV(32J4003)</h5>
    <a href="/charges/new" class="f"><h2>BUY</h2></a>
  </div>
  </div>
  <div class="column">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd5ifGIYvIDr6gjsXPqdmwighMlRNt3cx7bvZ4VxbFOTYnLMpsvkZ_nJuZ3Uki-KYaMkx5WUBI&usqp=CAc" style="width:50%"><div style="margin-left: 30px">
    <h5>Samsung 80cm (32 Inches) HD Ready LED TV UA32T4010ARXXL(Black)</h5>
    <a href="/charges/new" class="f"><h2>BUY</h2></a>
  </div>
  </div>
  <div class="column">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_esY0QJRtHSiIKcFKkLV9RFZkTEpFf-hk4bEJixXreoXf2EvJrKKd70dYxg&usqp=CAc"  style="width:50%"><div style="margin-left: 30px">
    <h5>Samsung 125cm (50 inch) Ultra HD (4K)LED Smart TV(UA50TUE60AKXXL)</h5>
    <a href="/charges/new" class="f"><h2>BUY</h2></a></div>
  </div>

  </div>

  <div class="column">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-P7vbYycxLb14-LsAf2mfvlFWYezWGOG0d9tSXAqzID-wyJq-EYNUUgRJ4ylFHUnHJYf0Uw&usqp=CAc" style="width:50%"><div style="margin-left: 30px">
    <h5>Samsung 80cm (32 inches) Wondertainment Series HD Ready LED TV</h5>
    <a href="/charges/new" class="f"><h2>BUY</h2></a></div>
  </div>
  <div class="column">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROwL7t6gCurt-3KbfhZIqQCjOZ5CcCyuYMwahJJhn3Hj9_PfMysyZKoAAuBSDr-wQdOlG9Tg&usqp=CAc" style="width:50%"><div style="margin-left: 30px">
    <h5>Samsung 108cm (43 inch) Full HD LED Smart TV, 5 Series43T5350</h5>
    <a href="/charges/new" class="f"><h2>BUY</h2></a></div>
  </div>
  <div class="column">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1k9tOLqw6EqB_VT0TREvPoXAeGtNRsHUPkUyCnD3wnXCl0gYjOiz4aPgWM0atI_Q2kHPzcJ0&usqp=CAc" style="width:50%"><div style="margin-left: 30px">
    <h5>Samsung 127cm (50 inch) Ultra HD (4K) LED Smart TV, 7 Series50TU7200</h5>
    <a href="/charges/new" class="f"><h2>BUY</h2></a></div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strip1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>